import { Platform } from 'react-native';

export type Eip1193Provider={request(args:{method:string;params?:unknown[]}):Promise<any>;on?:(event:string,listener:(...args:any[])=>void)=>void;removeListener?:(event:string,listener:(...args:any[])=>void)=>void;connect?:(options?:any)=>Promise<any>;disconnect?:()=>Promise<void>;session?:any;accounts?:string[]};
let walletConnectProvider:Eip1193Provider|null=null;let walletConnectInit:Promise<Eip1193Provider>|null=null;
function getInjectedProvider():Eip1193Provider|null{if(Platform.OS!=='web')return null;return (globalThis as any)?.ethereum??null;}
async function getWalletConnectProvider():Promise<Eip1193Provider>{if(walletConnectProvider)return walletConnectProvider;if(walletConnectInit)return walletConnectInit;walletConnectInit=(async()=>{const projectId=process.env.EXPO_PUBLIC_WALLETCONNECT_PROJECT_ID;if(!projectId)throw new Error('WalletConnect is not configured.');const{EthereumProvider}=await import('@walletconnect/ethereum-provider');const provider=await EthereumProvider.init({projectId,optionalChains:[56],showQrModal:true,methods:['eth_sendTransaction','personal_sign','eth_signTypedData','eth_signTypedData_v4'],events:['accountsChanged','chainChanged','disconnect'],metadata:{name:'MintGrow',description:'MintGrow Admin',url:process.env.EXPO_PUBLIC_APP_URL||'https://mintgrow.app',icons:[]},qrModalOptions:{enableMobileFullScreen:true}});walletConnectProvider=provider as unknown as Eip1193Provider;walletConnectInit=null;return walletConnectProvider;})().catch(e=>{walletConnectInit=null;throw e});return walletConnectInit;}
export async function getWalletProvider():Promise<Eip1193Provider>{return getInjectedProvider()??getWalletConnectProvider();}
export async function connectWallet():Promise<string>{const provider=await getWalletProvider();if(provider.connect&&!provider.session)await provider.connect();const accounts=await provider.request({method:'eth_requestAccounts'});const address=accounts?.[0]??provider.accounts?.[0];if(!address)throw new Error('No wallet address returned.');return address;}
export async function getChainId():Promise<number>{const p=await getWalletProvider();const id=await p.request({method:'eth_chainId'});return typeof id==='number'?id:Number.parseInt(String(id),16);}
export async function signTypedData(address:string,typedData:object):Promise<string>{const p=await getWalletProvider();return p.request({method:'eth_signTypedData_v4',params:[address,JSON.stringify(typedData)]});}
export function onchainConfig(){return{chainId:Number(process.env.EXPO_PUBLIC_MG_CHAIN_ID||56),delegation:process.env.EXPO_PUBLIC_MG_STAKE_DELEGATION||process.env.EXPO_PUBLIC_MG_DELEGATION_REGISTRY||'',mgsToken:process.env.EXPO_PUBLIC_MG_MGS_TOKEN||'',staking:process.env.EXPO_PUBLIC_MG_STAKING||'',apiUrl:process.env.EXPO_PUBLIC_MG_ONCHAIN_API_URL||''};}
export async function prepareStaking(address:string,amount:string,telegramId?:string){const c=onchainConfig();if(!c.apiUrl)throw new Error('MintGrow on-chain API is not configured.');const r=await fetch(`${c.apiUrl}/prepare-stake`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({address,amount,telegramId})});const b=await r.json();if(!r.ok)throw new Error(b?.error||'Unable to prepare staking authorization.');return b;}
export async function authorizeAndStake(address:string,telegramId:string|undefined,amount:string,preparation:any){const c=onchainConfig();if(!c.apiUrl||!c.delegation)throw new Error('MintGrow staking configuration is incomplete.');const typed={domain:{name:'MintGrow Stake Delegation',version:'1',chainId:c.chainId,verifyingContract:c.delegation},primaryType:'StakeAuthorization',types:{StakeAuthorization:[{name:'owner',type:'address'},{name:'relayer',type:'address'},{name:'staking',type:'address'},{name:'amount',type:'uint256'},{name:'nonce',type:'uint256'},{name:'deadline',type:'uint256'}]},message:{owner:address,relayer:preparation.sponsor,staking:c.staking,amount:amount,nonce:preparation.delegationNonce,deadline:preparation.deadline}};const signature=await signTypedData(address,typed);const r=await fetch(`${c.apiUrl}/submit-stake`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({address,telegramId,amount,delegation:{signature},voucher:preparation.voucher})});const b=await r.json();if(!r.ok)throw new Error(b?.error||'Sponsored staking submission failed.');return b;}
export async function sendStakingAdminTransaction(method:'approveStake'|'rejectStake',requestId:string){const c=onchainConfig();if(!c.staking)throw new Error('Staking contract is not configured.');const provider=await getWalletProvider();const accounts=await provider.request({method:'eth_requestAccounts'});const from=accounts?.[0];if(!from)throw new Error('Connect the staking multisig/admin wallet first.');const selector=method==='approveStake'?'0x'+await keccakSelector('approveStake(bytes32)'):'0x'+await keccakSelector('rejectStake(bytes32)');const data=selector+requestId.replace(/^0x/,'').padStart(64,'0');const txHash=await provider.request({method:'eth_sendTransaction',params:[{from,to:c.staking,data}]});return{txHash,from};}
async function keccakSelector(signature:string):Promise<string>{const response=await fetch(`${process.env.EXPO_PUBLIC_ONCHAIN_HASH_API||''}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({signature})});if(!response.ok)throw new Error('Contract transaction encoder is not configured.');const b=await response.json();return String(b.selector).replace(/^0x/,'').slice(0,8);}
