import AsyncStorage from '@react-native-async-storage/async-storage';
import { PlayerProfile, WithdrawalRequest, PowerUpType, DEFAULT_POWER_UPS, ReferralEntry } from '@/types/game';
import { verifiedApi } from '@/services/verifiedApi';

const KEYS = { PROFILE: 'mintgrow_profile_v4', DAILY_BONUS: 'mintgrow_daily_bonus_v2', SAVED_BOARD: 'mintgrow_saved_board' };
export const generateReferralCode = (telegramId: string): string => { const base = telegramId.replace(/\D/g, '').slice(-4) || '0000'; const suffix = Math.random().toString(36).substring(2, 5).toUpperCase(); return `MG${base}${suffix}`; };
export const createDefaultProfile = (telegramId: string, username: string): PlayerProfile => ({ telegramId, username, referralCode: '', referredBy: undefined, referralCount: 0, referralTokensEarned: 0, totalTokens: 0, pendingTokens: 0, withdrawnTokens: 0, walletAddress: '', level: 1, gamesPlayed: 0, bestScore: 0, adsWatched: 0, lastLoginDate: undefined, loginStreak: 0, powerUps: { ...DEFAULT_POWER_UPS }, isRegistered: false });
const mapRowToProfile = (row: any): PlayerProfile => ({ telegramId: String(row.telegram_id), username: row.username ?? 'CryptoPlayer', referralCode: row.referral_code ?? '', referredBy: row.referred_by ?? undefined, referralCount: Number(row.direct_referral_count ?? 0), referralTokensEarned: Number(row.referral_tokens_earned ?? 0), totalTokens: Number(row.total_tokens ?? 0), pendingTokens: Number(row.pending_tokens ?? 0), withdrawnTokens: Number(row.withdrawn_tokens ?? 0), walletAddress: row.wallet_address ?? '', level: Number(row.level ?? 1), gamesPlayed: Number(row.games_played ?? 0), bestScore: Number(row.best_score ?? 0), adsWatched: Number(row.ads_watched ?? 0), lastLoginDate: row.last_login_date ?? undefined, loginStreak: Number(row.login_streak ?? 0), powerUps: row.power_ups ?? { ...DEFAULT_POWER_UPS }, isRegistered: Boolean(row.is_registered) });
const cacheProfile = async (profile: PlayerProfile) => AsyncStorage.setItem(KEYS.PROFILE, JSON.stringify(profile));
export const getProfile = async (): Promise<PlayerProfile | null> => { try { const raw = await AsyncStorage.getItem(KEYS.PROFILE); if (!raw) return null; const p = JSON.parse(raw) as PlayerProfile; if (!p.powerUps) p.powerUps = { ...DEFAULT_POWER_UPS }; void syncProfileFromSupabase(p.telegramId); return p; } catch { return null; } };
export const syncProfileFromSupabase = async (telegramId: string): Promise<PlayerProfile | null> => { try { const row = await verifiedApi<any>('get_player', { telegramId }); if (!row) return null; const p = mapRowToProfile(row); await cacheProfile(p); return p; } catch { return null; } };
export const saveProfile = async (profile: PlayerProfile): Promise<void> => { await cacheProfile(profile); try { const row = await verifiedApi<any>('update_profile_metadata', { telegramId: profile.telegramId, username: profile.username, avatarUrl: profile.avatarUrl, walletAddress: profile.walletAddress, bestScore: profile.bestScore, level: profile.level, lastLoginDate: profile.lastLoginDate, loginStreak: profile.loginStreak }); if (row) await cacheProfile(mapRowToProfile(row)); } catch (error) { console.warn('Profile metadata sync failed:', error instanceof Error ? error.message : error); } };
export const initOrLoadProfile = async (telegramId: string, username: string, avatarUrl?: string): Promise<PlayerProfile> => { const row = await verifiedApi<any>('ensure_player', { telegramId, username, avatarUrl }); const p = mapRowToProfile(row); await cacheProfile(p); return p; };
export const updateProfileTokens = async (tokens: number, score: number): Promise<PlayerProfile | null> => { if (!Number.isFinite(tokens) || tokens <= 0) return getProfile(); const current = await getProfile(); if (!current) return null; try { const row = await verifiedApi<any>('credit_player_tokens', { telegramId: current.telegramId, amount: tokens, bestScore: score, level: Math.max(current.level || 1, (await import('@/services/gameEngine')).getLevelFromScore(score)) }); const p = mapRowToProfile(row); await cacheProfile(p); return p; } catch (error) { console.warn('Token credit failed:', error instanceof Error ? error.message : error); return current; } };
export const incrementAdsWatched = async (): Promise<void> => {};
export const addPowerUp = async (type: PowerUpType): Promise<PlayerProfile | null> => { const current = await getProfile(); if (!current) return null; try { const clientEventId = `powerup_${current.telegramId}_${type}_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`; const row = await verifiedApi<any>('grant_powerup', { telegramId: current.telegramId, type, clientEventId }); const p = mapRowToProfile(row); await cacheProfile(p); return p; } catch { return null; } };
export const usePowerUp = async (type: PowerUpType): Promise<PlayerProfile | null> => { const current = await getProfile(); if (!current) return null; try { const row = await verifiedApi<any>('consume_powerup', { telegramId: current.telegramId, type }); const p = mapRowToProfile(row); await cacheProfile(p); return p; } catch { return null; } };
export const spendTokensForPowerUp = async (type: PowerUpType, cost: number): Promise<PlayerProfile | null> => { const current = await getProfile(); if (!current) return null; try { const row = await verifiedApi<any>('spend_tokens_for_powerup', { telegramId: current.telegramId, type, cost }); const p = mapRowToProfile(row); await cacheProfile(p); return p; } catch { return null; } };
export interface DailyBonusState { lastClaimDate: string | null; streak: number; }
export const getDailyBonusState = async (): Promise<DailyBonusState> => { try { const raw = await AsyncStorage.getItem(KEYS.DAILY_BONUS); return raw ? JSON.parse(raw) : { lastClaimDate: null, streak: 0 }; } catch { return { lastClaimDate: null, streak: 0 }; } };
export const claimDailyBonus = async (): Promise<{ tokens: number; streak: number } | null> => { try { const result = await verifiedApi<any>('claim_daily_bonus'); if (!result?.ok) return null; await AsyncStorage.setItem(KEYS.DAILY_BONUS, JSON.stringify({ lastClaimDate: new Date().toDateString(), streak: Number(result.streak ?? 1) })); const profile = await getProfile(); if (profile?.telegramId) await syncProfileFromSupabase(profile.telegramId); return { tokens: Number(result.tokens ?? 0), streak: Number(result.streak ?? 1) }; } catch { return null; } };
export const getSavedBoard = async (): Promise<any | null> => { try { const raw = await AsyncStorage.getItem(KEYS.SAVED_BOARD); return raw ? JSON.parse(raw) : null; } catch { return null; } };
export const saveBoardState = async (state: any): Promise<void> => { try { await AsyncStorage.setItem(KEYS.SAVED_BOARD, JSON.stringify(state)); } catch {} };
export const clearSavedBoard = async (): Promise<void> => { try { await AsyncStorage.removeItem(KEYS.SAVED_BOARD); } catch {} };
const mapWithdrawal = (r: any): WithdrawalRequest => ({ id: String(r.id), telegramId: String(r.telegram_id), username: String(r.username), amount: Number(r.amount ?? 0), walletAddress: String(r.wallet_address ?? ''), network: String(r.network ?? ''), status: r.status as WithdrawalRequest['status'], createdAt: String(r.created_at), processedAt: r.processed_at ? String(r.processed_at) : undefined, txHash: r.tx_hash ? String(r.tx_hash) : undefined });
export const getWithdrawals = async (telegramId?: string): Promise<WithdrawalRequest[]> => { try { const id = telegramId || (await getProfile())?.telegramId; if (!id) return []; const rows = await verifiedApi<any[]>('get_withdrawals', { telegramId: id }); return (rows ?? []).map(mapWithdrawal); } catch { return []; } };
export const saveWithdrawal = async (req: WithdrawalRequest): Promise<void> => { await verifiedApi('submit_withdrawal_request', { id: req.id, telegramId: req.telegramId, username: req.username, amount: req.amount, walletAddress: req.walletAddress, network: req.network }); };
export const updateWithdrawal = async (_id: string, _updates: Partial<WithdrawalRequest>): Promise<void> => { throw new Error('Player withdrawal status changes are admin-only.'); };
export const getReferrals = async (referrerTelegramId?: string): Promise<ReferralEntry[]> => { try { const telegramId = referrerTelegramId || (await getProfile())?.telegramId; if (!telegramId) return []; const rows = await verifiedApi<any[]>('get_referrals', { telegramId }); return (rows ?? []).map((r: any) => ({ code: String(r.referee_telegram_id ?? ''), username: r.players?.username ?? 'Unknown', joinedAt: String(r.created_at), tokensEarned: Number(r.tokens_earned ?? 0), level: Number(r.level ?? 1), refereeBalance: Number(r.players?.total_tokens ?? 0) })); } catch { return []; } };
export const addReferral = async (_entry: ReferralEntry): Promise<void> => {};
export const applyReferralCode = async (code: string): Promise<boolean> => { try { const result = await verifiedApi<any>('apply_referral_code', { code: code.trim().toUpperCase() }); return Boolean(result?.ok); } catch { return false; } };
export interface LeaderboardEntry { rank: number; telegramId: string; username: string; totalTokens: number; level: number; bestScore: number; }
export const getLeaderboard = async (limit = 50): Promise<LeaderboardEntry[]> => { try { const rows = await verifiedApi<any[]>('get_leaderboard', { limit }); return (rows ?? []).map((row, i) => ({ rank: i + 1, telegramId: row.telegram_id, username: row.username, totalTokens: Number(row.total_tokens ?? 0), level: Number(row.level ?? 1), bestScore: Number(row.best_score ?? 0) })); } catch { return []; } };
export const getPlayerRank = async (_telegramId: string): Promise<number | null> => { try { return (await verifiedApi<number | null>('get_player_rank')) ?? null; } catch { return null; } };
export const subscribeWithdrawalUpdates = (_telegramId: string, _onUpdate: (withdrawal: WithdrawalRequest) => void) => () => {};
