const { ethers } = require('hardhat');
function envAddress(name){const v=process.env[name];if(!v)throw new Error(`${name} is required`);if(!ethers.isAddress(v))throw new Error(`${name} is not a valid address`);return v;}
async function wait(c){const tx=c.deploymentTransaction();if(tx)await tx.wait(1);} async function deploy(name,args=[]){const F=await ethers.getContractFactory(name);const c=await F.deploy(...args);await c.waitForDeployment();await wait(c);console.log(`${name}: ${await c.getAddress()}`);return c;} function same(a,b){return String(a).toLowerCase()===String(b).toLowerCase();} function assertOk(v,msg){if(!v)throw new Error(`WIRING CHECK FAILED: ${msg}`);}
async function main(){
 const [deployer]=await ethers.getSigners();const network=await ethers.provider.getNetwork();const chainId=Number(network.chainId);if(![56,97].includes(chainId))throw new Error(`Unsupported chain ${chainId}`);
 const multisig=envAddress('MULTISIG_ADDRESS'),sponsor=envAddress('SPONSOR_ADDRESS'),earningAttester=envAddress('EARNING_ATTESTER_ADDRESS');const initialRoiBps=BigInt(process.env.INITIAL_ROI_BPS||'100'),minRoiBps=BigInt(process.env.MIN_ROI_BPS||'0'),maxRoiBps=BigInt(process.env.MAX_ROI_BPS||'1000'),tokenAdminDelay=Number(process.env.TOKEN_ADMIN_DELAY||'0');
 const mg=await deploy('MGToken',[deployer.address,tokenAdminDelay]);const mgs=await deploy('MGSToken',[deployer.address,tokenAdminDelay]);const controller=await deploy('MintGrowControllerV2',[multisig,minRoiBps,maxRoiBps,initialRoiBps,true]);const stakingImpl=await deploy('MintGrowStakingV2');const delegationImpl=await deploy('MintGrowStakeDelegationV2');
 const SP=await ethers.getContractFactory('MintGrowStakingProxyV2');const stakingProxy=await SP.deploy(await stakingImpl.getAddress(),multisig,'0x');await stakingProxy.waitForDeployment();await wait(stakingProxy);const DP=await ethers.getContractFactory('MintGrowStakeDelegationProxyV2');const delegationProxy=await DP.deploy(await delegationImpl.getAddress(),multisig,'0x');await delegationProxy.waitForDeployment();await wait(delegationProxy);
 const rewardMinter=await deploy('MGStakingMinterV2',[multisig,await mg.getAddress(),await stakingProxy.getAddress()]);const staking=await ethers.getContractAt('MintGrowStakingV2',await stakingProxy.getAddress());const delegation=await ethers.getContractAt('MintGrowStakeDelegationV2',await delegationProxy.getAddress());
 await(await staking.initialize(multisig,await mgs.getAddress(),await mg.getAddress(),await delegationProxy.getAddress(),await rewardMinter.getAddress(),await controller.getAddress(),earningAttester)).wait(1);await(await delegation.initialize(multisig,sponsor,await stakingProxy.getAddress())).wait(1);
 const mgMinterRole=await mg.MINTER_ROLE(),mgsMinterRole=await mgs.MINTER_ROLE();await(await mg.grantRole(mgMinterRole,await rewardMinter.getAddress())).wait(1);await(await mgs.grantRole(mgsMinterRole,await stakingProxy.getAddress())).wait(1);const mgPauser=await mg.PAUSER_ROLE(),mgBlacklister=await mg.BLACKLISTER_ROLE(),mgsPauser=await mgs.PAUSER_ROLE(),mgsBlacklister=await mgs.BLACKLISTER_ROLE();await(await mg.grantRole(mgPauser,multisig)).wait(1);await(await mg.grantRole(mgBlacklister,multisig)).wait(1);await(await mgs.grantRole(mgsPauser,multisig)).wait(1);await(await mgs.grantRole(mgsBlacklister,multisig)).wait(1);await(await mg.renounceRole(mgPauser,deployer.address)).wait(1);await(await mg.renounceRole(mgBlacklister,deployer.address)).wait(1);await(await mgs.renounceRole(mgsPauser,deployer.address)).wait(1);await(await mgs.renounceRole(mgsBlacklister,deployer.address)).wait(1);
 assertOk(same(await controller.admin(),multisig),'controller admin');assertOk(same(await rewardMinter.admin(),multisig),'reward minter admin');assertOk(same(await rewardMinter.token(),await mg.getAddress()),'reward minter MG token');assertOk(same(await rewardMinter.staking(),await stakingProxy.getAddress()),'reward minter staking');assertOk(same(await staking.admin(),multisig),'staking admin');assertOk(same(await staking.mgs(),await mgs.getAddress()),'staking MGS');assertOk(same(await staking.mg(),await mg.getAddress()),'staking MG');assertOk(same(await staking.delegation(),await delegationProxy.getAddress()),'staking delegation');assertOk(same(await staking.rewardMinter(),await rewardMinter.getAddress()),'staking reward minter');assertOk(same(await staking.controller(),await controller.getAddress()),'staking controller');assertOk(same(await staking.earningAttester(),earningAttester),'staking earning attester');assertOk(same(await delegation.admin(),multisig),'delegation admin');assertOk(same(await delegation.sponsor(),sponsor),'delegation sponsor');assertOk(same(await delegation.staking(),await stakingProxy.getAddress()),'delegation staking');assertOk(await mgs.hasRole(mgsMinterRole,await stakingProxy.getAddress()),'MGS minter role');assertOk(await mg.hasRole(mgMinterRole,await rewardMinter.getAddress()),'MG reward minter role');assertOk((await staking.minimumStake())===ethers.parseEther('250000'),'minimum stake 250000');assertOk((await staking.minimumClaim())===ethers.parseEther('25000'),'minimum claim 25000');
 const addresses={chainId,deployer:deployer.address,multisig,sponsor,earningAttester,MGToken:await mg.getAddress(),MGSToken:await mgs.getAddress(),ControllerV2:await controller.getAddress(),MGStakingMinterV2:await rewardMinter.getAddress(),StakingImplementationV2:await stakingImpl.getAddress(),StakingProxyV2:await stakingProxy.getAddress(),DelegationImplementationV2:await delegationImpl.getAddress(),DelegationProxyV2:await delegationProxy.getAddress()};
 console.log('\n=== ALL V2 WIRING CHECKS PASSED ===\n'+JSON.stringify(addresses,null,2));console.log('\n=== MULTISIG TOKEN ADMIN HANDOFF ===');console.log(`MGToken.beginDefaultAdminTransfer(${multisig})`);console.log(`MGSToken.beginDefaultAdminTransfer(${multisig})`);console.log('Then multisig calls acceptDefaultAdminTransfer() on both tokens.');const fs=require('fs'),path=require('path');fs.mkdirSync(path.join(process.cwd(),'deployments'),{recursive:true});fs.writeFileSync(path.join(process.cwd(),'deployments',`bsc-v2-${chainId}.json`),JSON.stringify(addresses,null,2));
}
main().catch(e=>{console.error(e);process.exitCode=1;});
