-- Product decision: no game income cap. Server settlement still validates progression and is authoritative.
create or replace function public.settle_game_session(p_telegram_id text,p_client_session_id text,p_score integer,p_moves integer,p_level integer,p_max_tile integer,p_board jsonb default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare session_row public.game_sessions;player_row public.players;before_balance numeric;gameplay_reward numeric;level_reward numeric:=0;accepted numeric;derived_level integer:=1;i integer;level_rewards numeric[]:=array[50,100,250,500,1000,2000,4000,8000];score_thresholds integer[]:=array[0,500,1500,3500,7500,15000,30000,60000,120000];
begin
if p_score is null or p_score<0 or p_score>10000000 then raise exception 'Invalid score';end if;if p_moves is null or p_moves<1 or p_moves>10000 then raise exception 'Invalid move count';end if;if p_score>p_moves*10000 then raise exception 'Score progression is invalid';end if;if p_max_tile is null or p_max_tile<2 or p_max_tile>1073741824 then raise exception 'Invalid max tile';end if;
select * into session_row from game_sessions where client_session_id=trim(p_client_session_id) and telegram_id=p_telegram_id for update;if session_row.id is null then raise exception 'Game session not found';end if;if session_row.status<>'active' or session_row.settled_at is not null then return jsonb_build_object('ok',false,'reason','already_settled');end if;if now()<session_row.started_at+interval '2 seconds' then raise exception 'Game session ended too quickly';end if;if now()>session_row.started_at+interval '24 hours' then raise exception 'Game session expired';end if;
select * into player_row from players where telegram_id=p_telegram_id for update;if player_row.telegram_id is null then raise exception 'Player not found';end if;
for i in 1..8 loop if p_score>=score_thresholds[i] and player_row.level<i then level_reward:=level_reward+level_rewards[i];end if;end loop;for i in 1..array_length(score_thresholds,1) loop if p_score>=score_thresholds[i] then derived_level:=i;end if;end loop;
gameplay_reward:=round(p_score*0.12,2);accepted:=gameplay_reward+level_reward;before_balance:=player_row.total_tokens;
update players set total_tokens=round(total_tokens+accepted,2),best_score=greatest(best_score,p_score),level=greatest(level,derived_level),games_played=games_played+1 where telegram_id=p_telegram_id returning * into player_row;
update game_sessions set score=p_score,moves=p_moves,level=derived_level,tokens_earned=accepted,max_tile=p_max_tile,board=null,ended_at=now(),settled_at=now(),status='settled' where id=session_row.id;
if accepted>0 then insert into token_ledger(telegram_id,amount,balance_before,balance_after,reason,reference_type,reference_id,created_by) values(p_telegram_id,accepted,before_balance,player_row.total_tokens,'Server-settled game reward','game_session',session_row.id::text,'mintgrow-api');end if;
return jsonb_build_object('ok',true,'session_id',session_row.id,'gameplay_reward',gameplay_reward,'level_reward',level_reward,'reward',accepted,'level',player_row.level,'player',to_jsonb(player_row));end;$$;
revoke all on function public.settle_game_session(text,text,integer,integer,integer,integer,jsonb) from public,anon,authenticated;grant execute on function public.settle_game_session(text,text,integer,integer,integer,integer,jsonb) to service_role;
